set nocompatible
filetype off

set rtp+=$HOME/_vimfiles/bundle/Vundle.vim/
call vundle#begin('$HOME/_vimfiles/bundle/')
Plugin 'VundleVim/Vundle.vim'
Plugin 'dracula/vim'
Plugin 'scrooloose/nerdtree'
Plugin 'vim-airline/vim-airline'
Plugin 'vim-airline/vim-airline-themes'
call vundle#end()
filetype plugin indent on
syntax on
if !has("gui_running")
        set term=xterm
        set t_Co=256
        let &t_AB="\e[48;5;%dm"
        let &t_AF="\e[38;5;%dm"
        colorscheme dracula
endif
map <C-o> :NERDTreeToggle<CR>
set number
set relativenumber
set encoding=utf-8
set laststatus=2
set tabstop=2
set eb
set expandtab
set hlsearch
set ignorecase
set incsearch
set showcmd
set showmatch
set textwidth=80
set colorcolumn=100
set cursorline
set termguicolors
set noshowmode
let g:airline_symbols_ascii=1
"let g:airline_powerline_fonts = 1
"set guifont=Fira\ Code\ Medium:h9
